# 참고 : https://github.com/rickseven/dockerized-golang-mysql-api-sample/blob/master/docker-compose.yml
services:
  dreamus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    expose:
      - '3306'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}", "--execute=SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mysql_volume: